sudo: false
language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
- nightly
before_script:
- composer self-update
- composer dump-autoload
- composer install
script:
- phpunit tests
after_script:
- php vendor/bin/coveralls -v
before_install:
- openssl aes-256-cbc -K $encrypted_3f5a6849a5c1_key -iv $encrypted_3f5a6849a5c1_iv
  -in config.php.enc -out config.php -d
